#!/usr/bin/zsh
#
# Run all dotfiles installers.

echo $path_files

has_brew() { [[ -x `which brew` ]] }
is_mac() { [[ $OSTYPE == darwin* ]] }
is_freebsd() { [[ $OSTYPE == freebsd* ]] }
is_linux() { [[ $OSTYPE == linux-gnu ]] }

source ./brew/install.sh

for file in ${ZSH}/**/install.sh
do
  source $file
done


